#!/bin/sh
#/etc/init.d/mmtoperator

### BEGIN INIT INFO
# Provides:          mmtoperator
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: automatic crash report generation
### END INIT INFO


export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
  start)
  exec forever start /home/montimage/dev/mmt-operator/app.js -d mongo
  ;;
stop)
  exec forever stop /home/montimage/dev/mmt-operator/app.js
  ;;
*)
  echo "Usage: /etc/init.d/mmtoperator {start|stop}"
  exit 1
  ;;
esac

exit 0

